### PR TITLE
make app server command optional

### PR DESCRIPTION
**Pull request by svarks**
`web: touch /tmp/app-initialized && start-nginx`

### CODE REVIEW

**Comment by ejholmes** [comment]
:+1:

**Comment by jmontrose** [comment]
Couldn't you use the FORCE switch instead of making the app-less users touch that /tmp file?

**Comment by svarks** [comment]
@jmontrose I guess you can.. not sure how you specify it though, maybe something like  `start-nginx FORCE=true`. I'm not a bash expert :)

**Comment by svarks** [comment]
I looks like you can do `start-nginx -f`

**Comment by ejholmes** [comment]
Oh, good point. In Procfile, you could just do this I think:

```
web: env FORCE=true /bin/start-nginx
```

**Pull request closed without merging**
